version: '3.9'

services:
  azure-runner:
    container_name: azure-pipelines-agent
    build:
      context: ./
      dockerfile: Dockerfile
      tags:
        - dockeragent
      args:
        - HOST_UID: 2000
        - HOST_GID: 2000
    user: '2000:2000'  
    environment:
      AGENT_ALLOW_RUNASROOT: "1"
    env_file:
      - .env.azure
    volumes:
      - '${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock'
      - azure-work:/azp/_work
    restart: unless-stopped

volumes:
  azure-work:
