version: '3.9'

services:
  azure-runner:
    build:
      context: ./
      dockerfile: Dockerfile
      tags:
        - dockeragent
    container_name: azure-pipelines-agent
    env_file:
      - .env.azure
    volumes:
      - '${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock'
      - './azure-agent/_work:/azp/_work'
    command: bash -c 'chmod +x /azp-start.sh && /azp-start.sh'
    restart: unless-stopped
