version: '3.9'

services:
  azure-runner:
    container_name: azure-pipelines-agent
    build:
      context: ./
      dockerfile: Dockerfile
      tags:
        - dockeragent
    user: root  
    environment:
      AGENT_ALLOW_RUNASROOT: "1"
    env_file:
      - .env.azure
    volumes:
      - '${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock'
      - azure-work:/azp/_work
      - workspace:/workspace

    healthcheck:
      test: ["CMD", "pgrep", "Agent.Listener"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped

volumes:
  azure-work:
  workspace:
