version: '3.9'

services:
  azure-runner:
    environment:
      AGENT_ALLOW_RUNASROOT: "1"
    user: root  
    build:
      context: ./
      dockerfile: Dockerfile
      tags:
        - dockeragent
    container_name: azure-pipelines-agent
    env_file:
      - .env.azure
    volumes:
      - '${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock'
      - azure-work:/azp/_work
    restart: unless-stopped

volumes:
  azure-work:
