services:
  azure-runner:
    container_name: azure-pipelines-agent
    build:
      context: ./
      dockerfile: Dockerfile
      tags:
        - dockeragent
    user: root
    environment:
      # Expose build context for pipeline tasks
      AZP_BUILD_PATH: '${HOME}/.azurepipelinesagent/build'
      AZP_BUILD_DIR: 'build'
    env_file:
      - .env
    volumes:
      - '${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock'
      - '${HOME}/.azurepipelinesagent/build:/azp/build'

    healthcheck:
      test: ["CMD", "pgrep", "Agent.Listener"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped

